# golangci-lint configuration for EnumDNS
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - examples
    - testdata
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true

  golint:
    min-confidence: 0.8

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/helviojunior/enumdns

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
      - BUG
      - FIXME

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204  # Subprocess launched with variable
      - G301  # Poor file permissions used when creating a directory
      - G302  # Poor file permissions used with chmod
      - G304  # Potential file inclusion via variable

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  disable:
    - gochecknoglobals  # Allow globals for command-line tools
    - gocognit         # Disable cognitive complexity (using gocyclo instead)
    - funlen           # Disable function length check
    - godot            # Allow missing dots in comments

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - lll
        - goconst

    # Exclude some specific issues
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck

    # Exclude issues for CLI argument parsing
    - path: cmd/
      linters:
        - lll
        - gocyclo

    # Exclude issues in main.go
    - path: main\.go
      linters:
        - gochecknoinits

    # Allow long lines in documentation strings
    - source: "^//go:generate "
      linters:
        - lll

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: error
  rules:
    - linters:
        - dupl
        - goconst
        - lll
      severity: warning