package runner

var products = map[string][]string{
	"CloudFront":             {"cloudfront.net", "cloudfront"},
	"CloudFlare":             {"cloudflare.com", "cloudflare", "cc-ecdn.net"},
	"Akamai":                 {"akamaitechnologies.com", "edgekey.net", "akamaiedge.net", "akam.net"},
	"Imperva":                {"incapsula.com"},
	"Sucuri":                 {"sucuri.net"},
	"Bunny":                  {"bunnyinfra.net"},
	"KeyCDN":                 {"proinity.net"},
	"CDN77":                  {"cdn77.com"},
	"AWS Global Accelerator": {"awsglobalaccelerator.com"},
	"AWS":                    {"amazonaws.com", "awsdns"},
	"Microsoft Office 365":   {"lync.com", "office.com", "outlook.com"},
	"Microsoft Sharepoint":   {"sharepointonline.com"},
	"Azure":                  {"azure-dns.com", "azure-dns.net", "azure-dns.org", "azure-dns.info", "azurewebsites.net", "cloudapp.net"},
	"Oracle Cloud":           {"oraclecloud.net"},
	"GCP":                    {"googleusercontent.com"},
	"Registro.BR":            {"dns.br"},
}

var saas_products = map[string][]string{
	"CloudFront":                 {"cloudfront.net", "cloudfront"},
	"CloudFlare":                 {"cloudflare.com", "cloudflare", "cc-ecdn.net"},
	"Akamai":                     {"akamaitechnologies.com", "edgekey.net", "akamaiedge.net", "akam.net"},
	"Imperva":                    {"incapsula.com"},
	"Sucuri":                     {"sucuri.net"},
	"Bunny":                      {"bunnyinfra.net"},
	"KeyCDN":                     {"proinity.net"},
	"CDN77":                      {"cdn77.com"},
	"AWS Global Accelerator":     {"awsglobalaccelerator.com"},
	"Microsoft Office 365":       {"lync.com", "office.com", "outlook.com"},
	"Microsoft Sharepoint":       {"sharepointonline.com"},
	"Azure":                      {"azure-dns.com", "azure-dns.net", "azure-dns.org", "azure-dns.info", "azurewebsites.net"},
	"Heroku":                     {"herokuapp.com", "herokudns.com"},
	"Registro.BR":                {"dns.br"},
	"Trend Micro Email Security": {"tmes.trendmicro.com"},
	"Wix":                        {"wixsite.com", "wixdns.net"},
	"Github":                     {"github.io", "github.com"},
	"SalesForce":                 {"exacttarget.com"},
	"Shopify":                    {"myshopify.com"},
}

var datacenter = map[string][]string{
	"ALog":            {"alog.com.br"},
	"Toweb":           {"datacenter1.com.br"},
	"Uni5":            {"uni5.net"},
	"Hosting Service": {"hostingservice.com"},
	"Locaweb":         {"locaweb.com.br"},
	"Equinix":         {"equinix.com"},
	"Telefonica":      {"tdatabrasil.net.br"},
	"UOL":             {"uoldiveo.com.br", "compasso.com.br"},
	"HostGator":       {"hostgator.com.br"},
	"Datacom":         {"dialhost.com.br", "stackpath.net"},
	"DialHost":        {"brascloud.com.br", "dialhost.com.br"},
	"Oracle Cloud":    {"oraclecloud.com"},
}
